export const ADD_TOKEN = 'ADD_TOKEN'
export const ADD_USER = 'ADD_USER'
export const LOGOT = 'LOGOT'
export const LOGIN = 'LOGIN'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const ADD_BOOKS_USER = 'ADD_BOOKS_USER'
export const ADD_BOOK_USER = 'ADD_BOOK_USER'
export const UPDATE_BOOK_USER = 'UPDATE_BOOK_USER'
export const DELETE_BOOK_USER = 'DELETE_BOOK_USER'
export const FLAG = 'FLAG'

